"""Evidence report and the owner's annotation template.

Reads what compare / controls / equivalence / drift (and boot, when it ran)
wrote to the evidence directory and renders report.md plus
annotations.template.json. Every row the owner reviews gets `decision: null`;
an agent may fill `proposed` (from proposed.json: the causing commit, the
edge record, whether the change looks intended), never `decision`. Rows that
are identical across families collapse into one row carrying the family list.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import effective_config as ec

PROPOSED = ec.HERE / 'proposed.json'


def read(path, default=None):
    return path.read_text() if path.exists() else default


def load_json(path, default=None):
    return json.loads(path.read_text()) if path.exists() else default


def collapse(items):
    """[(key, family, payload)] -> {key: (payload, [families])}."""
    out = {}
    for key, family, payload in items:
        families = out.setdefault(key, (payload, []))[1]
        if family not in families:
            families.append(family)
    return out


def rows_from_compare(families):
    value, paired, names, neither, verdicts = [], [], [], {}, {}
    for fam in families:
        name = fam['family']
        verdicts[name] = fam['new']['verdict']
        for row in fam['rows']:
            if row['kind'] == 'paired':
                paired.append((f"{row['path']}:{row['effective']}", name, row))
                if row['effective'] != 'equal-effective':
                    value.append((f"R1:paired:{row['path']}:{row['old']}->{row['new']}", name, row))
            else:
                value.append((f"R1:{row['kind']}:{row['path']}:{row['old']}->{row['new']}", name, row))
        for n in fam['names']:
            if n['class'] in ('OLD_ONLY', 'NEW_ONLY', 'NO_EFFECT_AT_VALUE'):
                names.append((f"R2:{n['class']}:{n['name']}", name, n))
            if n['class'] == 'NEITHER':
                neither.setdefault(name, []).append(f"{n['name']} ({n['provenance']})")
    return collapse(value), collapse(paired), collapse(names), neither, verdicts


def notice_rows(boot):
    by = {(r['family'], r['side']): r for r in boot['results']}
    families = sorted({r['family'] for r in boot['results']})
    new, gone, same, derived, runtime = [], [], [], [], []
    for family in families:
        rc4, head = by.get((family, 'rc4')), by.get((family, 'head'))
        if not rc4 or not head:
            continue
        for side, result in (('rc.4', rc4), ('HEAD', head)):
            for n in result.get('runtime', []):
                runtime.append((f"{side}: {n['message']}", family, side))
        old = {n['message'] for n in rc4.get('notices', [])}
        levels = {n['message']: n['level'] for n in head.get('notices', [])}
        for message in sorted(set(levels) - old):
            new.append((f'R4:notice:new:{message}', family, levels[message]))
        for message in sorted(old - set(levels)):
            gone.append((f'R4:notice:gone:{message}', family, 'rc.4 only'))
        for message in sorted(old & set(levels)):
            same.append((message, family, levels[message]))
        for d in head.get('derived_diff_vs_rc4') or []:
            derived.append((f"R1:derived:{d['key']}:{d['rc4']}->{d['head']}", family, d))
    return collapse(new), collapse(gone), collapse(same), collapse(derived), collapse(runtime)


def md(text):
    return str(text).replace('|', '\\|').replace('\n', ' / ')


def table(header, rows):
    out = ['| ' + ' | '.join(header) + ' |', '| ' + ' | '.join('---' for _ in header) + ' |']
    out += ['| ' + ' | '.join(md(c) for c in row) + ' |' for row in rows]
    return out


def fams(names, total):
    return f'all {total}' if len(names) == total else ', '.join(names)


def cmd_report(args):
    out, work = Path(args.out), Path(args.work)
    families = [json.loads(p.read_text()) for p in sorted((out / 'families').glob('*.json'))]
    total = len(families)
    build = load_json(work / 'build.json', {})
    boot = load_json(out / 'boot.json')
    proposed = load_json(PROPOSED, {})
    controls = (read(out / 'controls.txt', '') + read(out / 'boot.txt', '')).splitlines()
    controls = [c for c in controls if c.startswith(('PASS', 'FAIL'))]
    value, paired, names, neither, verdicts = rows_from_compare(families)
    new = gone = same = derived = runtime = {}
    if boot:
        new, gone, same, derived, runtime = notice_rows(boot)
    by = {(r['family'], r['side']): r for r in (boot or {}).get('results', [])}
    lines = ['# Effective configuration: v0.2.0-rc.4 vs HEAD, per deployment family', '',
             'Generated by `scripts/effective-config/effective_config.py report` from this directory. '
             'Placeholders only: no value here is a real secret.', '', '## Provenance', '']
    head_commit = build.get('head_tree', {}).get('commit', '?')
    lines += [f"- rc.4: `{ec.OLD_TAG}` = {ec.git('rev-parse', ec.OLD_TAG + '^{commit}')}; old model "
              f"`{ec.OLD_MODEL_REV}` (injected dumper, never committed there); HEAD {head_commit}",
              f"- toolchain: {build.get('toolchain', '?')}; non-test dev builds, overflow checks and debug "
              'assertions off, one target directory per revision']
    for side in ('old-model', 'head', 'rc4', 'head-bin'):
        for name, a in build.get(side, {}).get('artifacts', {}).items():
            lines.append(f"- {side} `{name}` sha256 {a['sha256']} (commit {build[side]['commit'][:10]})")
    for p in sorted(Path(args.families).glob('*.family')):
        lines.append(f'- family `{p.name}` sha256 {hashlib.sha256(p.read_bytes()).hexdigest()}')
    lines += ['', '## Gates', '']
    lines += [f'- {line}' for line in read(out / 'equivalence/e1.txt', 'E1 missing').splitlines()[:1]]
    lines += [f'- {line}' for line in read(out / 'equivalence/e2.txt', 'E2 missing').splitlines()[:1]]
    e3 = load_json(out / 'equivalence/e3.json', [])
    lines.append(f"- E3: {len(e3)} knobs, {sum(1 for r in e3 if r['auto'] == 'equal')} defaults equal by "
                 f"evaluation, {sum(1 for r in e3 if r['auto'] == 'review')} for review, "
                 f"{sum(1 for r in e3 if r['auto'] == 'DIFFERENT')} DIFFERENT (`equivalence/e3-transcription.md`, "
                 'one owner decision)')
    lines += [f'- {c}' for c in controls]
    lines += ['', '## Families', '']
    header = ['family', 'source', 'HEAD validate', 'rc.4 boot', 'HEAD boot', 'value rows', 'OLD_ONLY', 'NEW_ONLY',
              'NO_EFFECT', 'NEITHER']
    rows = []
    for fam in families:
        counts = ec.count_classes(fam['names'])
        n_rows = sum(1 for r in fam['rows'] if r['kind'] != 'paired' or r['effective'] != 'equal-effective')
        rows.append([fam['family'], ', '.join(s for s, _ in fam['sources']) or '(binary defaults)',
                     fam['new']['verdict'].split('\n')[0],
                     by.get((fam['family'], 'rc4'), {}).get('verdict', 'not run'),
                     by.get((fam['family'], 'head'), {}).get('verdict', 'not run'), n_rows,
                     counts.get('OLD_ONLY', 0), counts.get('NEW_ONLY', 0), counts.get('NO_EFFECT_AT_VALUE', 0),
                     counts.get('NEITHER', 0)])
    lines += table(header, rows)
    lines += ['', '## Value rows (R1): changed effective fields', '']
    lines += table(['path', 'rc.4 model', 'HEAD', 'kind', 'families', 'proposed cause', 'proposed intended'],
                   [[p['path'], p['old'], p['new'], p['kind'], fams(f, total),
                     proposed.get(k, {}).get('commit', ''), proposed.get(k, {}).get('intended', '')]
                    for k, (p, f) in sorted(value.items())])
    lines += ['', 'Paired reader moves (46d4b7df, edge record #49), checked per family:', '']
    lines += table(['pair', 'families'], [[k, fams(f, total)] for k, (_, f) in sorted(paired.items())])
    if derived:
        lines += ['', 'Derived values served by both binaries while booted (C11: /v1/debug/absorb `config`, '
                  '/v1/debug/load compactor profile and SSE caps):', '']
        lines += table(['key', 'rc.4', 'HEAD', 'families'],
                       [[p['key'], p['rc4'], p['head'], fams(f, total)] for _, (p, f) in sorted(derived.items())])
    if boot:
        compared = sorted({r['family'] for r in boot['results'] if r['side'] == 'head' and r.get('derived')})
        missing = sorted({f"{r['family']} ({r['side']}: {', '.join(str(v.get('status')) for v in r['debug'].values())})"
                          for r in boot['results'] if r['verdict'] == 'BOOTED' and not r.get('derived')})
        keys = max((len(r['derived']) for r in boot['results'] if r.get('derived')), default=0)
        lines += ['', f"Derived values (C11): {keys} resolved keys compared per family in {len(compared)} families; "
                  f"{'no difference' if not derived else f'{len(derived)} differing keys (above)'}. Not available "
                  f"(debug surface is bearer-gated and the family sets no AUTH_TOKEN): {', '.join(missing) or 'none'}."]
    lines += ['', '## Names (R2, R3)', '']
    lines += table(['class', 'name', 'families', 'static read (rc.4 model / HEAD)'],
                   [[p['class'], p['name'], fams(f, total), f"{p['static_old']} / {p['static_new']}"]
                    for _, (p, f) in sorted(names.items())] or [['OLD_ONLY / NEW_ONLY', 'none', '', '']])
    probed = [(fam['family'], n) for fam in families for n in fam['names'] if n['class'] != 'PROCESS']
    disagree = sorted({f"{n['name']} ({side})" for _, n in probed for side, changed, static in
                       (('rc.4 model', n['old_changed'], n['static_old']), ('HEAD', n['new_changed'], n['static_new']))
                       if changed and not static})
    lines += ['', f"Static cross-check (C6b): {len(probed)} probed name rows; names the probe found honoured on a "
              f"side whose static name set lacks them: {', '.join(disagree) or 'none'}. Names in a static set that "
              'the probe saw no effect from are the NO_EFFECT_AT_VALUE rows above.']
    lines += ['', 'NEITHER (read by neither graph; provenance in brackets). R3 asks only whether any of these '
              'is a misspelled knob:', '']
    lines += [f"- {family}: {', '.join(items)}" for family, items in sorted(neither.items())]
    lines += ['', 'Overrides inside a family (a later --env beat an earlier one):', '']
    for fam in families:
        for name, old, new_value in fam['overridden']:
            lines.append(f"- {fam['family']}: {name} {old} -> {new_value}")
    if boot:
        lines += ['', '## Leg C: the real binaries booted against s3lite (R4)', '']
        lines += table(['family', 'rc.4', 'HEAD', 'substitutions (HEAD run)'],
                       [[f, by[(f, 'rc4')]['verdict'] + (f" exit {by[(f, 'rc4')]['exit_code']}"
                                                         if by[(f, 'rc4')]['exit_code'] is not None else ''),
                         by[(f, 'head')]['verdict'] + (f" exit {by[(f, 'head')]['exit_code']}"
                                                       if by[(f, 'head')]['exit_code'] is not None else ''),
                         '; '.join(by[(f, 'head')]['substitutions'])]
                        for f in sorted({r['family'] for r in boot['results']})])
        for f in sorted({r['family'] for r in boot['results']}):
            for side in ('rc4', 'head'):
                refusal = by[(f, side)].get('refusal')
                if refusal:
                    lines.append(f"- {f} {side} refusal: `{' / '.join(refusal)}`")
        lines += ['', 'Validation notices only HEAD logs (new):', '']
        lines += table(['level', 'notice', 'families'], [[p, k.split(':', 3)[3], fams(f, total)]
                                                         for k, (p, f) in sorted(new.items())] or [['', 'none', '']])
        lines += ['', 'Notices only rc.4 logs (gone at HEAD):', '']
        lines += table(['notice', 'families'], [[k.split(':', 3)[3], fams(f, total)]
                                                for k, (_, f) in sorted(gone.items())] or [['none', '']])
        lines += ['', 'Notices both log:', '']
        lines += table(['level', 'notice', 'families'], [[p, k, fams(f, total)] for k, (p, f) in sorted(same.items())])
        lines += ['', 'Runtime warnings of a fresh single process against s3lite (not configuration: they name no '
                  'configuration variable; listed for completeness, not reviewed):', '']
        lines += table(['side: warning', 'families'], [[k, fams(f, total)] for k, (_, f) in sorted(runtime.items())]
                       or [['none', '']])
        booted = sorted({r['family'] for r in boot['results'] if r['verdict'] == 'BOOTED'})
        differ = [f for f in booted if [b['message'] for b in by[(f, 'rc4')].get('budget', [])]
                  != [b['message'] for b in by[(f, 'head')].get('budget', [])]]
        lines += ['', f"Budget summary lines (R7: tokio workers, nofile, feed retention, the memory-budget line): "
                  f"identical on both sides in {len(booted) - len(differ)} of {len(booted)} booted runs"
                  f"{'; differing: ' + ', '.join(differ) if differ else ''}. Per family and side in `boot.json` "
                  '(`budget`) and `boot-logs/`.']
        for f in differ:
            for side in ('rc4', 'head'):
                lines += [f"- {f} {side}: {b['message']}" for b in by[(f, side)].get('budget', [])]
    lines += ['', '## Script drift (R6)', ''] + [f'    {line}' for line in read(out / 'drift.txt', '').splitlines()]
    template = annotations(value, names, neither, verdicts, boot, by, new, gone, derived, proposed, total)
    (out / 'annotations.template.json').write_text(json.dumps(template, indent=2) + '\n')
    lines += ['', '## Owner review', '',
              f"`annotations.template.json`: {len(template['rows'])} rows, every `decision` null. PASS needs P1-P6 "
              '(plan §2.7); P6 (a platform export per Compute project that will receive the binary) is not met '
              'by anything in this directory.']
    (out / 'report.md').write_text('\n'.join(lines) + '\n')
    print(f"report.md and annotations.template.json: {len(template['rows'])} rows for review")


def annotations(value, names, neither, verdicts, boot, by, new, gone, derived, proposed, total):
    rows = []

    def add(row_id, review, detail, families):
        rows.append({'id': row_id, 'review': review, 'families': families, 'detail': detail,
                     'proposed': proposed.get(row_id), 'decision': None})
    for key, (p, f) in sorted(value.items()):
        add(key, 'R1', f"{p['path']}: {p['old']} -> {p['new']}", f)
    for key, (p, f) in sorted(derived.items()):
        add(key, 'R1', f"{p['key']}: {p['rc4']} -> {p['head']}", f)
    for key, (p, f) in sorted(names.items()):
        add(key, 'R2', f"{p['name']} is {p['class']}", f)
    for family, items in sorted(neither.items()):
        add(f'R3:neither:{family}', 'R3', ', '.join(items), [family])
    for family, verdict in sorted(verdicts.items()):
        add(f'R4:validate:{family}', 'R4', f'HEAD validate: {verdict}', [family])
    if boot:
        for f in sorted({r['family'] for r in boot['results']} - {'k10-sweep-resident-0'}):
            add(f'R4:boot:{f}', 'R4', f"Leg C: rc.4 {by[(f, 'rc4')]['verdict']}, HEAD {by[(f, 'head')]['verdict']}", [f])
        for key, (p, f) in sorted(new.items()):
            add(key, 'R4', f'new {p} notice at HEAD', f)
        for key, (_, f) in sorted(gone.items()):
            add(key, 'R4', 'notice rc.4 logged that HEAD does not', f)
    add('R5:e3', 'R5', 'E3 transcription table (equivalence/e3-transcription.md)', [])
    add('R6:drift', 'R6', 'rc.4-era vs HEAD-era --env names (drift.txt)', [])
    add('R7:budget', 'R7', 'boot-log budget summaries, rc.4 vs HEAD (eyeball)', [])
    return {'comment': 'decision: accept | reject, set by the owner only. proposed: filled by an agent from '
                       'scripts/effective-config/proposed.json (cause and intent), never a decision.',
            'families': total, 'rows': rows}
