import {
  SCHEMA_REGISTRY_API_VERSION,
  type SchemaRegistry,
  type SearchConfig,
} from "../../schema/registry";

export const METRICS_CANONICAL_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    apiVersion: { type: "string", const: "durable.streams/metrics/v1" },
    kind: { type: "string", const: "interval" },
    metric: { type: "string" },
    unit: { type: "string" },
    metricKind: { type: "string" },
    temporality: { type: "string" },
    windowStart: { type: "integer" },
    windowEnd: { type: "integer" },
    intervalMs: { type: "integer" },
    instance: { type: ["string", "null"] },
    stream: { type: ["string", "null"] },
    tags: {
      type: "object",
      additionalProperties: { type: "string" },
    },
    attributes: {
      type: "object",
      additionalProperties: { type: "string" },
    },
    dimensionPairs: {
      type: "array",
      items: { type: "string" },
    },
    dimensionKey: { type: ["string", "null"] },
    seriesKey: { type: "string" },
    count: { type: "number" },
    sum: { type: "number" },
    min: { type: ["number", "null"] },
    max: { type: ["number", "null"] },
    avg: { type: "number" },
    p50: { type: "number" },
    p95: { type: "number" },
    p99: { type: "number" },
    buckets: {
      type: "object",
      additionalProperties: { type: "number" },
    },
    summary: {
      type: "object",
      additionalProperties: false,
      properties: {
        count: { type: "number" },
        sum: { type: "number" },
        min: { type: ["number", "null"] },
        max: { type: ["number", "null"] },
        histogram: {
          type: "object",
          additionalProperties: { type: "number" },
        },
      },
      required: ["count", "sum", "min", "max", "histogram"],
    },
  },
  required: [
    "apiVersion",
    "kind",
    "metric",
    "unit",
    "metricKind",
    "temporality",
    "windowStart",
    "windowEnd",
    "intervalMs",
    "instance",
    "stream",
    "tags",
    "attributes",
    "dimensionPairs",
    "dimensionKey",
    "seriesKey",
    "count",
    "sum",
    "min",
    "max",
    "avg",
    "p50",
    "p95",
    "p99",
    "buckets",
    "summary",
  ],
} as const;

export const METRICS_DEFAULT_SEARCH_CONFIG: SearchConfig = {
  profile: "metrics",
  primaryTimestampField: "windowStart",
  aliases: {
    ts: "windowStart",
    time: "windowStart",
    name: "metric",
    dims: "dimensionKey",
    series: "seriesKey",
  },
  defaultFields: [
    { field: "metric", boost: 2 },
    { field: "stream", boost: 1.25 },
    { field: "dimensionPairs", boost: 1 },
  ],
  fields: {
    windowStart: {
      kind: "date",
      bindings: [{ version: 1, jsonPointer: "/windowStart" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    windowEnd: {
      kind: "date",
      bindings: [{ version: 1, jsonPointer: "/windowEnd" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
    },
    intervalMs: {
      kind: "integer",
      bindings: [{ version: 1, jsonPointer: "/intervalMs" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    metric: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/metric" }],
      normalizer: "lowercase_v1",
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    unit: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/unit" }],
      normalizer: "lowercase_v1",
      exact: true,
      prefix: true,
      exists: true,
      aggregatable: true,
    },
    metricKind: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/metricKind" }],
      normalizer: "lowercase_v1",
      exact: true,
      prefix: true,
      exists: true,
      aggregatable: true,
    },
    temporality: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/temporality" }],
      normalizer: "lowercase_v1",
      exact: true,
      prefix: true,
      exists: true,
      aggregatable: true,
    },
    stream: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/stream" }],
      normalizer: "lowercase_v1",
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    instance: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/instance" }],
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    seriesKey: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/seriesKey" }],
      exact: true,
      exists: true,
      sortable: true,
    },
    dimensionKey: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/dimensionKey" }],
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    dimensionPairs: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/dimensionPairs" }],
      exact: true,
      prefix: true,
      exists: true,
    },
    count: {
      kind: "integer",
      bindings: [{ version: 1, jsonPointer: "/count" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    sum: {
      kind: "float",
      bindings: [{ version: 1, jsonPointer: "/sum" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    min: {
      kind: "float",
      bindings: [{ version: 1, jsonPointer: "/min" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
    },
    max: {
      kind: "float",
      bindings: [{ version: 1, jsonPointer: "/max" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
    },
    avg: {
      kind: "float",
      bindings: [{ version: 1, jsonPointer: "/avg" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
    },
    p95: {
      kind: "float",
      bindings: [{ version: 1, jsonPointer: "/p95" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
    },
    p99: {
      kind: "float",
      bindings: [{ version: 1, jsonPointer: "/p99" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
    },
  },
  rollups: {
    metrics: {
      timestampField: "windowStart",
      dimensions: ["metric", "unit", "stream", "instance", "dimensionKey", "metricKind", "temporality"],
      intervals: ["10s", "1m", "5m", "1h"],
      measures: {
        value: {
          kind: "summary_parts",
          countJsonPointer: "/count",
          sumJsonPointer: "/sum",
          minJsonPointer: "/min",
          maxJsonPointer: "/max",
          histogramJsonPointer: "/buckets",
        },
      },
    },
  },
};

export function buildMetricsDefaultRegistry(stream: string): SchemaRegistry {
  return {
    apiVersion: SCHEMA_REGISTRY_API_VERSION,
    schema: stream,
    currentVersion: 1,
    routingKey: { jsonPointer: "/seriesKey", required: true },
    search: structuredClone(METRICS_DEFAULT_SEARCH_CONFIG),
    boundaries: [{ offset: 0, version: 1 }],
    schemas: {
      "1": structuredClone(METRICS_CANONICAL_SCHEMA),
    },
    lenses: {},
  };
}

