import {
  SCHEMA_REGISTRY_API_VERSION,
  type SchemaRegistry,
  type SearchConfig,
} from "../../schema/registry";

export const EVLOG_CANONICAL_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    timestamp: { type: "string" },
    level: { type: "string", enum: ["debug", "info", "warn", "error"] },
    service: { type: ["string", "null"] },
    environment: { type: ["string", "null"] },
    version: { type: ["string", "null"] },
    region: { type: ["string", "null"] },
    requestId: { type: ["string", "null"] },
    traceId: { type: ["string", "null"] },
    spanId: { type: ["string", "null"] },
    method: { type: ["string", "null"] },
    path: { type: ["string", "null"] },
    status: { type: ["integer", "null"] },
    duration: { type: ["number", "null"] },
    message: { type: ["string", "null"] },
    why: { type: ["string", "null"] },
    fix: { type: ["string", "null"] },
    link: { type: ["string", "null"] },
    sampling: {
      type: ["object", "null"],
      additionalProperties: true,
    },
    redaction: {
      type: "object",
      additionalProperties: false,
      properties: {
        keys: {
          type: "array",
          items: { type: "string" },
        },
      },
      required: ["keys"],
    },
    context: {
      type: "object",
      additionalProperties: true,
    },
  },
  required: [
    "timestamp",
    "level",
    "service",
    "environment",
    "version",
    "region",
    "requestId",
    "traceId",
    "spanId",
    "method",
    "path",
    "status",
    "duration",
    "message",
    "why",
    "fix",
    "link",
    "sampling",
    "redaction",
    "context",
  ],
} as const;

export const EVLOG_DEFAULT_SEARCH_CONFIG: SearchConfig = {
  profile: "evlog",
  primaryTimestampField: "timestamp",
  aliases: {
    env: "environment",
    msg: "message",
    req: "requestId",
    span: "spanId",
    time: "timestamp",
    trace: "traceId",
    ts: "timestamp",
  },
  defaultFields: [
    { field: "message", boost: 2 },
    { field: "why", boost: 1.5 },
    { field: "fix", boost: 1.25 },
    { field: "error.message", boost: 2 },
  ],
  fields: {
    timestamp: {
      kind: "date",
      bindings: [{ version: 1, jsonPointer: "/timestamp" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    level: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/level" }],
      normalizer: "lowercase_v1",
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    service: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/service" }],
      normalizer: "lowercase_v1",
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    environment: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/environment" }],
      normalizer: "lowercase_v1",
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    requestId: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/requestId" }],
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
    },
    traceId: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/traceId" }],
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
    },
    spanId: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/spanId" }],
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
    },
    path: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/path" }],
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    method: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/method" }],
      normalizer: "lowercase_v1",
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    status: {
      kind: "integer",
      bindings: [{ version: 1, jsonPointer: "/status" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    duration: {
      kind: "float",
      bindings: [{ version: 1, jsonPointer: "/duration" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    message: {
      kind: "text",
      bindings: [{ version: 1, jsonPointer: "/message" }],
      analyzer: "unicode_word_v1",
      exists: true,
      positions: true,
    },
    why: {
      kind: "text",
      bindings: [{ version: 1, jsonPointer: "/why" }],
      analyzer: "unicode_word_v1",
      exists: true,
      positions: true,
    },
    fix: {
      kind: "text",
      bindings: [{ version: 1, jsonPointer: "/fix" }],
      analyzer: "unicode_word_v1",
      exists: true,
      positions: true,
    },
    "error.message": {
      kind: "text",
      bindings: [{ version: 1, jsonPointer: "/context/error/message" }],
      analyzer: "unicode_word_v1",
      exists: true,
      positions: true,
    },
  },
};

export function buildEvlogDefaultRegistry(stream: string): SchemaRegistry {
  return {
    apiVersion: SCHEMA_REGISTRY_API_VERSION,
    schema: stream,
    currentVersion: 1,
    search: structuredClone(EVLOG_DEFAULT_SEARCH_CONFIG),
    boundaries: [{ offset: 0, version: 1 }],
    schemas: {
      "1": structuredClone(EVLOG_CANONICAL_SCHEMA),
    },
    lenses: {},
  };
}
